### ISSUE TITLE
Notify users of a randomly generated seed

### ISSUE THREAD

**Issue by Minoru** [Minoru/plentyfs#13]
If the filesystem was mounted without `-o seed=…` (#5), PlentyFS would generate a random seed. We should log it somewhere, in case the user finds the generated FS interesting and would like to generate it again sometime later.

Since PlentyFS can conceivably be mounted not just manually but also via `mount` and /etc/fstab, it's an interesting question of where to log the seed: no-one might be around to read stdout, and syslog/journald might be an unexpected place to look.

**Comment by larswirzenius** [comment]
I'd be OK with syslog/journald, but what about a .plentyfs-random-seed at the mount point?

**Comment by Minoru** [comment]
Oh, that's a great idea! I'll go with that. Thanks!
